apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BoxiSun/python-docker-eks.git
    targetRevision: HEAD
    path: flask-app-deployment/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: flask
  syncPolicy:
    automated:
      selfHeal: true